//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Args.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Args.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a value after {0}.
        /// </summary>
        internal static string ArgsMissingValue {
            get {
                return ResourceManager.GetString("ArgsMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booleans with a default value are not meaningful.  If the switch exists, the value is true, otherwise the value is false..
        /// </summary>
        internal static string BoolWithDefaultInModel {
            get {
                return ResourceManager.GetString("BoolWithDefaultInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not derive short name for member {0} in type {1}. Most likely another member name starts with &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidMemberName {
            get {
                return ResourceManager.GetString("InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not derive short name for member {0} in type {1}. It is not in the list of possible members to pick from..
        /// </summary>
        internal static string MemberNotFoundInAvailableMembers {
            get {
                return ResourceManager.GetString("MemberNotFoundInAvailableMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable boolean values can not be bound in a meaningful way, please consider using Boolean or an Enum..
        /// </summary>
        internal static string NullableBoolInModel {
            get {
                return ResourceManager.GetString("NullableBoolInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find appropriate type converter from type {0} to type {1}..
        /// </summary>
        internal static string TypeConverterNotFoundMessage {
            get {
                return ResourceManager.GetString("TypeConverterNotFoundMessage", resourceCulture);
            }
        }
    }
}
